name: Docker Image CI

on: 
  push:
    branches:
    - master
  schedule:
  - cron: "0 1 * * 1"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Login to github docker registry
      run: docker login -u Ducatel -p ${{ secrets.GITHUB_TOKEN }} docker.pkg.github.com
    - name: Build the latest image
      run: docker build --file Dockerfile --tag Ducatel/visual-studio-linux-build-box/vs-linux-build-box:latest .
    - name: Push latest image
      run: docker push docker.pkg.github.com/Ducatel/visual-studio-linux-build-box/vs-linux-build-box:latest
    - name: Build the image with ubuntu 18.04
      run: docker build --file Dockerfile --tag Ducatel/visual-studio-linux-build-box/vs-linux-build-box:18.04 .
    - name: Push 18.04 image
      run: docker push docker.pkg.github.com/Ducatel/visual-studio-linux-build-box/vs-linux-build-box:18.04
    - name: Build the image with ubuntu 16.04
      run: docker build --file ubuntu1604-Dockerfile --tag Ducatel/visual-studio-linux-build-box/vs-linux-build-box:16.04 .
    - name: Push 16.04 image
      run: docker push docker.pkg.github.com/Ducatel/visual-studio-linux-build-box/vs-linux-build-box:16.04
